title: Mansi Phute
tagline: CS PhD Student at Georgia Tech
email: mansiphute@gatech.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of the site, e.g. /blog
url: https://mphute.github.io/ # the base hostname & protocol for the site


# Build settings
sass:
  sass_dir: _sass
  style: compressed

author:
  name: Mansi Phute
  url: https://mphute.github.io/
  email: mansiphute@gatech.edu

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'

excerpt_separator: <!--more-->

#theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
