# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           "/:title"
# relative_permalinks: true

# Setup
title: Mansi Phute
tagline: M.S. Student at GT
url: mphute.github.io
# gems:                [jekyll-paginate]
# paginate:            5
baseurl: ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

# About/contact
author:
  name: Mansi Phute
  url: https://twitter.com/mansiphute
  email: mphute6@gatech.edu

# Custom vars
version: 2.0.0
github:
  repo: https://mphute/mphute.github.io

nav_list:
  Home: "/"
  CV: "/cv"
  # Projects: '/projects'
  # Blog: '/blog'
  Publications: "/cv#publications"
  # Everything Else: '/everything-else'

# paginate_path: "blog/page:num/"

excerpt_separator: <!--more-->
